const firstname = 'Samuel';
firstname = 'Pablo';
const lastname = 'Enikanolaye';
const age = 27;
const dateOfBirth = '09/16/1991';
const address = '178 Tallgrass Crescent';
console.log('firstName: ', firstname);
console.log('lastName: ', lastname);
console.log('age: ', age);
console.log('dateOfBirth: ', dateOfBirth);
console.log('address: ', address);