const firstName = 'Samuel';
const lastName = 'Enikanolaye';
const age = 27;
const dateOfBirth = '09/16/1991';
const address = '178 Tallgrass Crescent';
console.log('firstName: ', firstName);
console.log('lastName: ', lastName);
console.log('age: ', age);
console.log('dateOfBirth: ', dateOfBirth);
console.log('address: ', address);